export interface Customer {
    uuid: string;
    id: number;
    first_name: string;
    last_name: string ;
    phone: string ;
    fax: string;
    email: string;
    receiver_priority :string,
    sender_priority :string,
    market_customer :string,
    name :string,
    grid_id :string,
    is_active :string,
    subject_to_TVA :string,
    activity_id :string,
    customer_type :string,
    code :string,
    Adress_1 :string,
    pays :string,
    port_pays :string,
    delay_invoice :string,
    refund_delay :string,
    tva :string,
    ville :string,
    Social_reason :string,
    Adress_2 :string,
    ICE :string,
    sec_activity :string,
    potential :string,
    Port_du :string,
    deadline :string,
    exemplary_number :string,
    references :string,
    GMS :string,
    is_prospect :string,
    type :string,
    use_grid :string,
    potentiel :string,
    city_id :string,
    id_parent :string,
    logo_path :string,
    entreprise_name :string,
    identity_number :string,
    logistic_first_name :string,
    logistic_last_name :string,
    logistic_email :string,
    logistic_phone :string,
    sector_id :string,
    colis_potentiel :string,
    created_at: string;
    updated_at: string;
  }