import { from } from 'rxjs';

export * from './login/login.component';
export * from './home/home.component';
export * from './dashboard/dashboard.component';
export * from './reclamations/reclamations.component';
export * from './grille-tarifaire/tarifaire-tab-groupe/tarifaire-tab-groupe.component';
export * from './list-template/list-template.component';
export * from './offer-commerciales/offer-commerciales.component';
export * from './grille-tarifaire/add-version/add-version.component';
export * from './parametre/parametre-tab-groupe/parametre-tab-groupe.component';
export * from './gestion-rdvs/gestion-rdvs.component';
export * from './gestion-tasks/gestion-tasks.component';
export * from './gestion-contacts/gestion-contacts.component';
export * from './gestion-comptes-client/gestion-comptes-client.component';
export * from './gestion-prospects/gestion-prospects.component';
export * from './gestions-devis/gestions-devis.component';
export * from './gestions-devis/historique-versions/historique-versions.component';
export * from './tournees/tournees.component';
export * from './tournees/details-tournees/details-tournees.component';
export * from './dispatch-arrivage/parc-tab-groupe/parc-tab-groupe.component';
export * from './gestion-vehicules/administrative-tab-groupe/administrative-tab-groupe.component';
export * from './feuille-route/gestion-disponibilites/tab-gestion-disponibilites/tab-gestion-disponibilites.component';
export * from './feuille-route/affectation/tab-affectation/tab-affectation.component';
export * from './document-administrative/documentadmin-groupe/documentadmin-groupe.component';
export * from './affretement/liste-clients/steps-reservations/steps-reservations.component';
export * from './grille-affretement/affretement-tab-groupe/affretement-tab-groupe.component'

export * from './dashboard/dashboard.module';
export * from './home/home.module';
export * from './reclamations/reclamations.module';
export * from './grille-tarifaire/grille-tarifaire.module';
export * from './parametre/parametre.module';
export * from './list-template/list-template.module';
export * from './dispatch-arrivage/gestion-de-parc.module';
export * from './gestion-vehicules/gestion-vehicules.module';
export * from './feuille-route/gestion-disponibilites/tab-gestion-disponibilites.module';
export * from './feuille-route/affectation/tab-affectation.module';
export * from './document-administrative/tab-groupe-documentadmnistrative.module';
export * from './grille-affretement/grille-affretement.module'
