export enum ExpeditionStatus {
  DRAFT = 'DRAFT',
  CREATED = 'CREATED',
  PLANED = 'PLANED',
  COLLECTED = 'COLLECTED',
  IN_HUB = 'IN_HUB',
  ON_THE_WAY = 'ON_THE_WAY',
  ARRIVES_AT_DESTINATION = 'ARRIVES_AT_DESTINATION',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  CANCELED = 'CANCELED',
}
